update:
	/bin/bash update.sh

# run only if you're sure that you want to bump version and you're sure that there is something that should be pushed to npm registry
update-force:
	/bin/bash update.sh force
